# thanks https://github.com/joshrotenberg for his example
# https://github.com/joshrotenberg/wtd-bayarea-mdbook

[book]
authors = ["alex zonov"]
language = "en"
multilingual = false
src = "src"
title = "Attic - last resort for my notes"

[rust]
edition = "2021"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/anzome/attic/tree/main"
# cname = "attic.anzo.me"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2